import type {NextPage} from 'next'
import Head from 'next/head'
import Grid from "../src/components/Grid/Grid";
import SliderOnePicture from "../src/components/SliderOnePicture/SliderOnePicture";
import SliderSmallDot from "../src/components/SliderSmallDot/SliderSmallDot";
import Tabs from "../src/components/Tabs/Tabs";


const Home: NextPage = () => {


    return (
        <Grid>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <SliderOnePicture/>
            <SliderSmallDot />
            <Tabs />
        </Grid>
    )
}

export default Home
