import type { NextPage } from 'next'
import Head from 'next/head'
import Grid from "../components/Grid/Grid";

const Home: NextPage = () => {
  return (
   <Grid>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <h1>ggg</h1>

   </Grid>
  )
}

export default Home
