import type {NextPage} from 'next'
import Head from 'next/head'
import Grid from "../src/components/Grid/Grid";
import trueFalse from "../hooks/TrueFalse/TrueFalse";
import Slider from "../src/components/Slider/Slider";



const Home: NextPage = () => {

    const [isVisible, toogleVisible] = trueFalse<boolean>(true)

    return (
        <Grid>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


            <Slider></Slider>

        </Grid>
    )
}

export default Home
